In [1]:
import pandas as pd
import numpy as np
import os
import nltk as nltk

In [2]:
dir_path = '../google_data/NLP_data/'

In [3]:
data_path = os.path.join(dir_path, 'ART_AND_DESIGN.csv')
data_rev = pd.read_csv(data_path)
print(data_rev.shape)
data_rev.head()

(548, 5)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,3D Color Pixel by Number - Sandbox Art Coloring,NaN,NaN,0.182146,0.492704
1,3D Color Pixel by Number - Sandbox Art Coloring,NaN,NaN,0.182146,0.492704
2,3D Color Pixel by Number - Sandbox Art Coloring,NaN,NaN,0.182146,0.492704
3,3D Color Pixel by Number - Sandbox Art Coloring,NaN,NaN,0.182146,0.492704
4,3D Color Pixel by Number - Sandbox Art Coloring,NaN,NaN,0.182146,0.492704

In [4]:
import glob

read_files = glob.glob(r'/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/*.csv')

print(read_files)

['/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/PARENTING.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/HEALTH_AND_FITNESS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/VIDEO_PLAYERS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/EDUCATION.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/NEWS_AND_MAGAZINES.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/SOCIAL.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/FINANCE.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/ART_AND_DESIGN.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/PERSONALIZATION.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/HOUSE_AND_HOME.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/LIFESTYLE.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/PRODUCTIVITY.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/BUSINESS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/TRAVEL_AND_LOCAL.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/COMMUNICATION.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/BOOKS_AND_REFERENCE.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/SHOPPING.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/FAMILY.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/SPORTS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/FOOD_AND_DRINK.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/WEATHER.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/TOOLS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/ENTERTAINMENT.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/DATING.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/PHOTOGRAPHY.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/EVENTS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/AUTO_AND_VEHICLES.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/BEAUTY.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/LIBRARIES_AND_DEMO.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/MAPS_AND_NAVIGATION.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/MEDICAL.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/COMICS.csv', '/Users/jianweicheng/Desktop/ＮＴＵＴ/碩一下/3-2 CRM/期末報告/google_data/NLP_data/GAME.csv']

In [5]:
arrange_data = []
for line in read_files:
    line = line.split('/') # 將每句最後的 \t 取代成空值後，再以逗號斷句
    arrange_data.append(line)
arrange_data

[['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'PARENTING.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'HEALTH_AND_FITNESS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'VIDEO_PLAYERS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'EDUCATION.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'NEWS_AND_MAGAZINES.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'SOCIAL.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'FINANCE.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'ART_AND_DESIGN.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'PERSONALIZATION.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'HOUSE_AND_HOME.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'LIFESTYLE.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'PRODUCTIVITY.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'BUSINESS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'TRAVEL_AND_LOCAL.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'COMMUNICATION.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'BOOKS_AND_REFERENCE.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'SHOPPING.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'FAMILY.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'SPORTS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'FOOD_AND_DRINK.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'WEATHER.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'TOOLS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'ENTERTAINMENT.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'DATING.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'PHOTOGRAPHY.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'EVENTS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'AUTO_AND_VEHICLES.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'BEAUTY.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'LIBRARIES_AND_DEMO.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'MAPS_AND_NAVIGATION.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'MEDICAL.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'COMICS.csv'],
 ['',
  'Users',
  'jianweicheng',
  'Desktop',
  'ＮＴＵＴ',
  '碩一下',
  '3-2 CRM',
  '期末報告',
  'google_data',
  'NLP_data',
  'GAME.csv']]

In [6]:
from nltk.stem.porter import PorterStemmer
porter_stemmer = PorterStemmer()
from nltk.stem.lancaster import LancasterStemmer
lancaster_stemmer = LancasterStemmer()
from nltk.stem import SnowballStemmer
snowball_stemmer = SnowballStemmer('english')
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

df = pd.DataFrame(arrange_data)
df.head()
df_cat = df[10]

print(len(read_files))

category = []
num_rev = []
for f in range(len(read_files)):

    data_rev = pd.read_csv(read_files[f], sep=',', encoding='utf_8_sig')

#     print(df1["Category"])

    data = data_rev[['Sentiment','Translated_Review']]
    data = data[data.Sentiment!= 'NaN']
    
    data1 = data[['Translated_Review']]
    data1 = data1.dropna()
    data2 = np.array(data1['Translated_Review'])
    data2
    
    category.append(df_cat[f])
    num_rev.append(len(data2))
#     result = []
#     for i in range(len(data2)):

#         testStr = data2[i]

#         tokens = i = nltk.word_tokenize(testStr)
#     #     print(tokens)
#         result += i
#     #     tokens = nltk.wordpunct_tokenize(testStr) ## 請注意，差異在cut-off
#     #     print(tokens)
    
#     groups = result

#     ironmen_dict = {
#                     "result": groups
#     }

#     ironmen_df = pd.DataFrame(ironmen_dict)
#     ironmen_df
#     ironmen_df["result"].value_counts()
    
#     a1 = ironmen_df["result"].value_counts()
#     # a1 = pd.value_counts(result)
#     a1 = pd.DataFrame(a1)

33

In [7]:
category

['PARENTING.csv',
 'HEALTH_AND_FITNESS.csv',
 'VIDEO_PLAYERS.csv',
 'EDUCATION.csv',
 'NEWS_AND_MAGAZINES.csv',
 'SOCIAL.csv',
 'FINANCE.csv',
 'ART_AND_DESIGN.csv',
 'PERSONALIZATION.csv',
 'HOUSE_AND_HOME.csv',
 'LIFESTYLE.csv',
 'PRODUCTIVITY.csv',
 'BUSINESS.csv',
 'TRAVEL_AND_LOCAL.csv',
 'COMMUNICATION.csv',
 'BOOKS_AND_REFERENCE.csv',
 'SHOPPING.csv',
 'FAMILY.csv',
 'SPORTS.csv',
 'FOOD_AND_DRINK.csv',
 'WEATHER.csv',
 'TOOLS.csv',
 'ENTERTAINMENT.csv',
 'DATING.csv',
 'PHOTOGRAPHY.csv',
 'EVENTS.csv',
 'AUTO_AND_VEHICLES.csv',
 'BEAUTY.csv',
 'LIBRARIES_AND_DEMO.csv',
 'MAPS_AND_NAVIGATION.csv',
 'MEDICAL.csv',
 'COMICS.csv',
 'GAME.csv']

In [8]:
num_rev

[260,
 2249,
 331,
 847,
 1040,
 741,
 1435,
 382,
 1003,
 511,
 954,
 1463,
 1082,
 1692,
 1024,
 651,
 898,
 2009,
 1479,
 638,
 201,
 1451,
 1264,
 1715,
 1176,
 158,
 289,
 338,
 333,
 192,
 1400,
 45,
 6678]

In [9]:
nrev_dict = {
                    "cateogry": category,
                    "number_rev": num_rev
}

nrev_df = pd.DataFrame(nrev_dict)
nrev_df
# ironmen_df["result"].value_counts()

                   cateogry  number_rev
0             PARENTING.csv         260
1    HEALTH_AND_FITNESS.csv        2249
2         VIDEO_PLAYERS.csv         331
3             EDUCATION.csv         847
4    NEWS_AND_MAGAZINES.csv        1040
5                SOCIAL.csv         741
6               FINANCE.csv        1435
7        ART_AND_DESIGN.csv         382
8       PERSONALIZATION.csv        1003
9        HOUSE_AND_HOME.csv         511
10            LIFESTYLE.csv         954
11         PRODUCTIVITY.csv        1463
12             BUSINESS.csv        1082
13     TRAVEL_AND_LOCAL.csv        1692
14        COMMUNICATION.csv        1024
15  BOOKS_AND_REFERENCE.csv         651
16             SHOPPING.csv         898
17               FAMILY.csv        2009
18               SPORTS.csv        1479
19       FOOD_AND_DRINK.csv         638
20              WEATHER.csv         201
21                TOOLS.csv        1451
22        ENTERTAINMENT.csv        1264
23               DATING.csv        1715
24          PHOTOGRAPHY.csv        1176
25               EVENTS.csv         158
26    AUTO_AND_VEHICLES.csv         289
27               BEAUTY.csv         338
28   LIBRARIES_AND_DEMO.csv         333
29  MAPS_AND_NAVIGATION.csv         192
30              MEDICAL.csv        1400
31               COMICS.csv          45
32                 GAME.csv        6678

In [15]:
nrev_df.sort_values('number_rev', ascending = False).head(10)
#找出前5筆資料做文字雲

                  cateogry  number_rev
32                GAME.csv        6678
1   HEALTH_AND_FITNESS.csv        2249
17              FAMILY.csv        2009
23              DATING.csv        1715
13    TRAVEL_AND_LOCAL.csv        1692
18              SPORTS.csv        1479
11        PRODUCTIVITY.csv        1463
21               TOOLS.csv        1451
6              FINANCE.csv        1435
30             MEDICAL.csv        1400

In [14]:
proportion = []
for i in range(len(nrev_df)):
    a = nrev_df["number_rev"]
    b = a[i] / sum(nrev_df["number_rev"])
    proportion.append(b)
prop_dict = {"category":category,"proportion" : proportion} 
prop_df = pd.DataFrame(prop_dict)
c1 = prop_df['proportion'].sort_values(ascending = False)
c2 = prop_df['proportion'].sort_values(ascending = False).cumsum()
prop_dict = {"category":category,"proportion" : c1, "cumsum" : c2}
prop_df = pd.DataFrame(prop_dict)
prop_df.head(10)

                  category  proportion    cumsum
32           PARENTING.csv    0.185867  0.185867
1   HEALTH_AND_FITNESS.csv    0.062596  0.248462
17       VIDEO_PLAYERS.csv    0.055916  0.304378
23           EDUCATION.csv    0.047733  0.352111
13  NEWS_AND_MAGAZINES.csv    0.047093  0.399204
18              SOCIAL.csv    0.041165  0.440369
11             FINANCE.csv    0.040719  0.481088
21      ART_AND_DESIGN.csv    0.040385  0.521473
6      PERSONALIZATION.csv    0.039940  0.561413
30      HOUSE_AND_HOME.csv    0.038966  0.600379

35929